package user;
// Generated May 18, 2013 11:04:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Userreg generated by hbm2java
 */
public class Userreg  implements java.io.Serializable {


     private Integer eid;
     private String ename;
     private String password;

    public Userreg() {
    }

    public Userreg(String ename, String password) {
       this.ename = ename;
       this.password = password;
    }
   
    public Integer getEid() {
        return this.eid;
    }
    
    public void setEid(Integer eid) {
        this.eid = eid;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
}


